AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Scryscraper Lambda that fetches MTG card data from Scryfall API and stores it in DynamoDB and S3

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name
    AllowedValues:
      - dev
      - staging
      - prod
      - exp

Conditions:
  IsExpEnvironment: !Equals [!Ref Environment, exp]
  IsNotExpEnvironment: !Not [!Equals [!Ref Environment, exp]]

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - arm64

Resources:
  # S3 Bucket for caching Scryfall API responses
  ScryscraperCacheBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: !If [IsExpEnvironment, Delete, Retain]
    UpdateReplacePolicy: !If [IsExpEnvironment, Delete, Retain]
    Properties:
      BucketName: !Sub monorepo-fem-scryscraper-cache-${Environment}
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # DynamoDB Table for storing MTG card data
  ScryscraperTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: !If [IsExpEnvironment, Delete, Retain]
    UpdateReplacePolicy: !If [IsExpEnvironment, Delete, Retain]
    Properties:
      TableName: !Sub monorepo-fem-scryscraper-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  # Lambda's execution log group (exp environment with Delete policy)
  ScryscraperLogGroupDelete:
    Type: AWS::Logs::LogGroup
    Condition: IsExpEnvironment
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/lambda/scryscraper-${Environment}
      RetentionInDays: 7

  # Lambda's execution log group (non-exp environments with Retain policy)
  ScryscraperLogGroupRetain:
    Type: AWS::Logs::LogGroup
    Condition: IsNotExpEnvironment
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/scryscraper-${Environment}
      RetentionInDays: 7

  # IAM Role for Lambda Function
  ScryscraperFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub scryscraper-lambda-role-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ScryscraperS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:HeadObject
                Resource: !Sub ${ScryscraperCacheBucket.Arn}/*
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt ScryscraperCacheBucket.Arn
        - PolicyName: ScryscraperDynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:Query
                Resource:
                  - !GetAtt ScryscraperTable.Arn
                  - !Sub ${ScryscraperTable.Arn}/index/*

  # Lambda Function
  ScryscraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub scryscraper-${Environment}
      Description: Fetches MTG card data from Scryfall API and stores it in DynamoDB and S3
      CodeUri: dist/
      Handler: index.handler
      Role: !GetAtt ScryscraperFunctionRole.Arn
      Environment:
        Variables:
          NODE_ENV: !Ref Environment
          SCRYSCRAPER_CACHE_BUCKET: !Ref ScryscraperCacheBucket
          DYNAMODB_TABLE: !Ref ScryscraperTable
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Name: !Sub scryscraper-schedule-${Environment}
            Description: Triggers Scryscraper every minute
            Enabled: true

  # CloudWatch Alarm for Lambda Errors
  ScryscraperErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AlarmName: !Sub scryscraper-errors-${Environment}
      AlarmDescription: Alerts when the Scryscraper Lambda function encounters errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ScryscraperFunction
      TreatMissingData: notBreaching

  # CloudWatch Alarm for Lambda Throttles
  ScryscraperThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AlarmName: !Sub scryscraper-throttles-${Environment}
      AlarmDescription: Alerts when the Scryscraper Lambda function is throttled
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ScryscraperFunction
      TreatMissingData: notBreaching

  # CloudWatch Alarm for Lambda Duration approaching timeout
  ScryscraperDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AlarmName: !Sub scryscraper-duration-${Environment}
      AlarmDescription: Alerts when the Scryscraper Lambda function duration exceeds 80% of timeout (24s of 30s)
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 24000
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ScryscraperFunction
      TreatMissingData: notBreaching

  # Log Metric Filter for 429 errors (Scryfall rate limiting)
  RateLimitMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: '"429"'
      LogGroupName: !If
        - IsExpEnvironment
        - !Ref ScryscraperLogGroupDelete
        - !Ref ScryscraperLogGroupRetain
      MetricTransformations:
        - MetricName: ScryfallRateLimitHit
          MetricNamespace: !Sub Scryscraper/${Environment}
          MetricValue: '1'
          DefaultValue: 0

  # CloudWatch Alarm for 429 rate limit errors
  RateLimitAlarm:
    Type: AWS::CloudWatch::Alarm
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AlarmName: !Sub scryscraper-rate-limit-${Environment}
      AlarmDescription: Alerts when Scryscraper encounters Scryfall API rate limiting (HTTP 429)
      MetricName: ScryfallRateLimitHit
      Namespace: !Sub Scryscraper/${Environment}
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

Outputs:
  ScryscraperFunction:
    Description: Name of the Scryscraper Lambda function
    Value: !Ref ScryscraperFunction
  ScryscraperCacheBucket:
    Description: Name of the S3 cache bucket
    Value: !Ref ScryscraperCacheBucket
  ScryscraperTable:
    Description: Name of the DynamoDB table
    Value: !Ref ScryscraperTable
