AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: TS Lambda publishes heartbeats to CloudWatch Logs every minute via EventBridge

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name
    AllowedValues:
      - dev
      - staging
      - prod

Globals:
  Function:
    Timeout: 4
    MemorySize: 128
    Runtime: nodejs20.x
    Architectures:
      - arm64

Resources:
  # CloudWatch Log Group where heartbeat logs will be published
  # Created BEFORE the Lambda to ensure CloudFormation owns it
  HeartbeatsLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub /monorepo-fem/ts-heartbeat-${Environment}
      RetentionInDays: 1

  # Lambda's own execution log group (for monitoring the Lambda itself)
  # Created BEFORE the Lambda to ensure CloudFormation owns it
  HeartbeatPublisherLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/lambda/ts-heartbeat-publisher-${Environment}
      RetentionInDays: 7

  # Lambda Function that publishes logs
  HeartbeatPublisherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ts-heartbeat-publisher-${Environment}
      Description: Publishes heartbeat logs to CloudWatch on a schedule
      CodeUri: dist/
      Handler: index.handler
      Environment:
        Variables:
          LOG_GROUP_NAME: !Ref HeartbeatsLogGroup
          LOG_STREAM_PREFIX: heartbeat
          NODE_ENV: !Ref Environment
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !GetAtt HeartbeatsLogGroup.Arn
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Name: !Sub ts-heartbeat-publisher-schedule-${Environment}
            Description: Triggers Heartbeat Publisher every minute
            Enabled: true
